trigger:
- main

pool:
  name: Continus Integration Continuous Delivery Agent
  demands:
    - agent.name -equals MR-ROBOT

variables:
  backDirectory: 'Back-End'
  buildDirectory: 'target'
  productionDirectory: 'C:\site\E-commerce\Back-End'

steps:
- checkout: self

- powershell: |
   $source = "https://corretto.aws/downloads/latest/amazon-corretto-8-x86-windows-jdk.zip"
   $destination = "$(build.sourcesdirectory)\amazon-corretto-8.412.08.1-windows-x86-jdk.zip"
   $client = new-object System.Net.WebClient 
   $client.downloadFile($source, $destination)
  displayName: 'PowerShell Script'
  
- task: JavaToolInstaller@0
  displayName: 'Use Java 1.8 corretto'
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: '$(build.sourcesdirectory)\amazon-corretto-8.412.08.1-windows-x86-jdk.zip'
    jdkDestinationDirectory: '$(build.sourcesdirectory)\jdk1.8.0_412'

- task: Maven@3
  displayName: 'build backend'
  inputs:
    mavenPomFile: 'Back-End/pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
  
- script: |
    cd $(Build.SourcesDirectory)\$(backDirectory)
    docker compose up --no-start
  displayName: 'Déployer l application dans docker compose'